
;plant name,plant group name,multiplexer address in hexidecimal,port that sensor is on
soilsensor=African Voilet,Violets,0x70,0
soilsensor=Wobbly Nunu,Fake Plants,0x70,1
soilsensor=Christmas Cactus,Cacti,0x70,2

;plantgroup=plant group name,green threshold,yellow threshold,over-water threshold
plantgroup=Violets,530,330,700
plantgroup=Fake Plants,580,450,600
plantgroup=Cacti,300,100,400

temperatureUnits=fahrenheit
temperatureOffset=-7

;END